name: Test and upload Python package

on:
  pull_request:
  push:
    branches: [master]
    tags:
      - 'v*'
      - '!v*-dev'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # Test Zeek LTS, latest, and nightly, and
        # don't fail for the nightly one.
        include:
          - repo: zeek
            version: latest
            experimental: false
          - repo: zeek
            version: lts
            experimental: false
          - repo: zeek-dev
            version: latest
            experimental: true

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container:
      image: zeek/${{ matrix.repo }}:${{ matrix.version }}

    steps:
      - name: Install build environment
        run: |
          apt-get update
          apt-get install -y --no-install-recommends cmake g++ libssl-dev libpcap-dev make
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          make test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: btest-${{ matrix.repo }}-${{ matrix.version }}
          path: testing/.tmp/

  upload:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.repository == 'zeek/package-manager' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Check release version
        # This fails e.g. if VERSION contains a dev commits suffix,
        # since we don't want to push these to PyPI. Accepts two-
        # and three-component version numbers (e.g. 1.0 and 1.0.1).
        run: |
          grep -E -x '[0-9]+\.[0-9]+(\.[0-9]+)?' VERSION
      - name: Build wheel
        run: |
          make dist
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
